[project]
name = 'Decentralized-Advertising-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ad]
path = 'contracts/ad.clar'
clarity_version = 2
epoch = 2.5

[contracts.publisher]
path = 'contracts/publisher.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
